name: game_leaderboard_client
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  go_router: ^8.0.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
